path_data: "./data"
path_metadata: "./data/metadata.csv"

#VHR arch and enc
architecture : "unet" 
encoder : "resnet34" 
encoder_weights: None


#For fine tuning
resume_training: False
decoder_only: False

weight_pth : "./model/checkpoints/best_checkpoint_epoch=23_val_meanF1Score=0.81_val_loss=0.22.ckpt"


out_folder: "./data/predictions/baseline/"
out_model_name: "model"

# Augmentation
use_augmentation: False

# Data Normalization
Norm_function: "quantile"
q_low: [15, 26, 24, 75, 0]
q_hi: [162, 158, 148, 239, 186]

# Weighting
include_background: True
index_background: None
weights_classes:
                         background : [0.1]
                         bark beetle : [0.25]
                         clear-cut : [0.25]
                         windthrow : [0.4]
                       
# Inputs
num_classes: 4
vhr_hw: [500,500]
target_size: [512,512]
num_channels_aerial: 5 

# Inference
batch_size_inference: 128
save_predictions: False
metric_path: "./data/predictions/metrics"


# Optimizer config
lr: 0.0001

#LR scheduler
factor: 0.1
mode: "min"
monitor: "val_loss"
patience: 3

# Computation
num_workers: 1