path_data: "./data"
path_metadata: "./data/metadata.csv"

#VHR arch and enc
architecture : ["unet"] 
encoder : ["resnet34"] 
encoder_weights: None


#For fine tuning
resume_training: True
decoder_only: False
previous_num_classes: 19

weight_pth : "./flair_1_weights/FLAIR-INC_rgbie_15cl_resnet34-unet_weights.pth"


out_folder: "./model/"
out_model_name: "model"

# Augmentation
use_augmentation: True

# Data Normalization
Norm_function: "quantile"
q_low: [15, 26, 24, 75, 0]
q_hi: [162, 158, 148, 239, 186]


# Weighting
include_background: True
index_background: None
weights_classes:
                         background : [0.1]
                         bark beetle : [0.25]
                         clear-cut : [0.25]
                         windthrow : [0.4]
                       
# Inputs
num_classes: 4
vhr_hw: [500,500]
target_size: [512,512]
num_channels_aerial: 5 

# Training
num_epochs: 100
early_stopping_patience: 50
batch_size: 32
batch_size_inference: 1
deterministic_mode: "warn"

# Optimizer config
lr: 0.0001

#LR scheduler
factor: 0.1
mode: "min"
monitor: "val_loss"
patience: 3

# Computation
seed: 2024
num_workers: 4
accelerator: "gpu"
gpus_per_node: "auto"
num_nodes: 1
strategy: "ddp" 